Progress... the SVDLoader complains about some concurrency issue now:
<__main__.MemoryRegion instance at 0x14a>, <__main__.MemoryRegion instance at 0x14b>, <__main__.MemoryRegion instance at 0x14c>, <__main__.MemoryRegion instance at 0x14d>, <__main__.MemoryRegion instance at 0x14e>, <__main__.MemoryRegion instance at 0x14f>, <__main__.MemoryRegion instance at 0x150>, <__main__.MemoryRegion instance at 0x151>]
Traceback (most recent call last):
  File "/Users/romanvg/ghidra_scripts/svd-loader/SVD-Loader.py", line 121, in <module>
    t = currentProgram.memory.createUninitializedBlock(r.name, addr, length, False)
  File "/Users/romanvg/ghidra_scripts/svd-loader/SVD-Loader.py", line 121, in <module>
    t = currentProgram.memory.createUninitializedBlock(r.name, addr, length, False)
	at ghidra.framework.data.DomainObjectAdapter.checkExclusiveAccess(DomainObjectAdapter.java:365)
	at ghidra.program.database.mem.MemoryMapDB.createUninitializedBlock(MemoryMapDB.java:704)
	at jdk.internal.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
ghidra.framework.store.LockException: ghidra.framework.store.LockException: Operation requires exclusive access to object.

After a few changes there (other than the SVD xml BlockAddress section).

/cc @trufae

diff --git a/SVD-Loader.py b/SVD-Loader.py
index f82a6dd..3433ab0 100644
--- a/SVD-Loader.py
+++ b/SVD-Loader.py
@@ -9,6 +9,7 @@
 # https://leveldown.de/blog/svd-loader/
 # License: GPLv3

+import sys
 from cmsis_svd.parser import SVDParser
 from ghidra.program.model.data import Structure, StructureDataType, UnsignedIntegerDataType, DataTypeConflictHandler
 from ghidra.program.model.data import UnsignedShortDataType, ByteDataType, UnsignedLongLongDataType
@@ -70,15 +71,15 @@ cpu_endian = parser.get_device().cpu.endian
 default_register_size = parser.get_device().size

 # Not all SVDs contain these fields
-if cpu_type and not cpu_type.startswith("CM"):
-	print("Currently only Cortex-M CPUs are supported.")
-	print("Supplied CPU type was: " + cpu_type)
-	sys.exit(1)
+#if cpu_type and not cpu_type.startswith("CM"):
+#	print("Currently only Cortex-M CPUs are supported.")
+#	print("Supplied CPU type was: " + cpu_type)
+#	sys.exit(1)

-if cpu_endian and cpu_endian != "little":
-	print("Currently only little endian CPUs are supported.")
-	print("Supplied CPU endian was: " + cpu_endian)
-	sys.exit(1)
+#if cpu_endian and cpu_endian != "little":
+#	print("Currently only little endian CPUs are supported.")
+#	print("Supplied CPU endian was: " + cpu_endian)
+#	sys.exit(1)

 # Get things we need
 listing = currentProgram.getListing()
@@ -96,13 +97,20 @@ print("Generating memory regions...")
 # First, we need to generate a list of memory regions.
 # This is because some SVD files have overlapping peripherals...
 memory_regions = []
+
+flipper = lambda n:int('0'+bin(n)[3:],2)
+
 for peripheral in peripherals:
-	start = peripheral.base_address
+	start = flipper(peripheral.base_address)
 	length = peripheral.address_block.offset + peripheral.address_block.size
-	end = peripheral.base_address + length
+	end = flipper(peripheral.base_address) + length

+        print(peripheral.name + ": \t\t" + hex(start) + " to " + hex(end))
 	memory_regions.append(MemoryRegion(peripheral.name, start, end))
+
 memory_regions = reduce_memory_regions(memory_regions)
+print("Resulting memory reducing is:\n")
+print(memory_regions)

 # Create memory blocks:
 for r in memory_regions: