As expected python's CMSIS-SVD validation fails with the generated SVD:
$ ./bin/verify.py
Traceback (most recent call last):
  File "./bin/verify.py", line 5, in <module>
    for peripheral in parser.get_device().peripherals:
  File "/Users/romanvg/.miniconda3/envs/reveng/lib/python3.7/site-packages/cmsis_svd/parser.py", line 339, in get_device
    return self._parse_device(self._root)
  File "/Users/romanvg/.miniconda3/envs/reveng/lib/python3.7/site-packages/cmsis_svd/parser.py", line 334, in _parse_device
    reset_mask=_get_int(device_node, "resetMask")
  File "/Users/romanvg/.miniconda3/envs/reveng/lib/python3.7/site-packages/cmsis_svd/model.py", line 390, in __init__
    self.address_unit_bits = _check_type(address_unit_bits, six.integer_types)
  File "/Users/romanvg/.miniconda3/envs/reveng/lib/python3.7/site-packages/cmsis_svd/model.py", line 40, in _check_type
    actual_type=type(value),
TypeError: Value None has unexpected type <class 'NoneType'>, expected (<class 'int'>,)

Scanned datasheet for more tables... almost all of those will require
some data wrangling, but they are fairly consistent across the datasheet
anyway.